site_url: https://devops.isc.heia-fr.ch/
site_name: DevOps
site_description: DevOps / DevOps appliqué
copyright: "Copyright &copy; {{ cal.today.year }} Haute école d'ingénierie et d'architecture of Fribourg"

extra:
  show_page_revision_on_all_pages: false
  teacher_name: "Jacques Supcik"
  year: "2024-2025"
  teams_name: DevOps - ID3
  teams_code: n0bptfr
  class_names:
    - ISC-ID-3

  consent:
    title: Utilisation des cookie
    description: >-
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos
      préférences, ainsi que pour mesurer l'efficacité de notre documentation
      et déterminer si les utilisateurs trouvent ce qu'ils recherchent.
      Avec votre consentement, vous nous aidez à améliorer notre documentation.
  social:
    - icon: material/microsoft-teams
      link: https://teams.microsoft.com/l/team/19%3a1MW2cVOrZ_s5iAyWcBpGRgXYTwfNPiO97yme__t8osk1%40thread.tacv2/conversations?groupId=155b46a4-7016-4c52-960f-6db7a7b0ce13&tenantId=a372f724-c0b2-4ea0-abfb-0eb8c6f84e40
    - icon: material/web
      link: https://www.heia-fr.ch/fr/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/heiafr.htafr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HEIAFR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/heiafr/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/heiafr
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/eiafr

theme:
  name: material
  language: "fr"
  font:
    text: "Roboto"
    code: "IBM Plex Mono"
  custom_dir: "overrides/"
  icon:
    logo: material/school
  favicon: "assets/images/favicon.ico"
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - content.tabs.link

extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  admonition: {}
  extra: {}
  smarty:
    smart_angled_quotes: true
    substitutions:
      left-angle-quote: "&laquo;&#xA0;"
      right-angle-quote: "&#xA0;&raquo;"
  mkdcomments: {}
  footnotes: {}
  codehilite: {}
  pymdownx.arithmatex:
    generic: true
  pymdownx.betterem:
    smart_enable: all
  pymdownx.tabbed: {}
  pymdownx.highlight: {}
  pymdownx.caret: {}
  pymdownx.critic: {}
  pymdownx.details: {}
  pymdownx.keys: {}
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  pymdownx.inlinehilite: {}
  pymdownx.magiclink: {}
  pymdownx.mark: {}
  pymdownx.smartsymbols: {}
  pymdownx.superfences: {}
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.tilde: {}
  mdx_math: {}
  attr_list: {}
  md_in_html: {}

plugins:
  - search
  - calendar
  - jconfig:
      items:
        - copyright
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - awesome-pages
  - macros
  - pages-j2
