INHERIT: base.yml
site_url: https://devops.isc.heia-fr.ch/
site_name: DevOps
site_description: DevOps / DevOps appliqué

extra:
  show_page_revision_on_all_pages: false
  teacher_name: "Jacques Supcik"
  year: "2022-2023"

  teams_name: DevOps - ID3
  teams_code: mzb6ojm
  class_names:
    - ISC-ID-3
  social:
    - icon: material/microsoft-teams
      link: https://teams.microsoft.com/l/team/19%3a1MW2cVOrZ_s5iAyWcBpGRgXYTwfNPiO97yme__t8osk1%40thread.tacv2/conversations?groupId=155b46a4-7016-4c52-960f-6db7a7b0ce13&tenantId=a372f724-c0b2-4ea0-abfb-0eb8c6f84e40
    - icon: material/web
      link: https://www.heia-fr.ch/fr/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/heiafr.htafr
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HEIAFR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/heiafr/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/heiafr
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/eiafr
